/// A struct representing a single timeoff received from bob.
#[allow(dead_code)]
pub struct Timeoff {
    id: i64,
    // latest_state: dict,
    // actions: list,
    approved_by: Option<u64>,
    can_edit: bool,
    // date_range: dict,
    description: Option<String>,
    // documents: list,
    duration: i64,
    duration_description: Option<String>,
    employee_id: String,
    end_date: String,
    end_date_portion: String,
    // events: list,
    policy_type: String,
    policy_type_display_name: String,
    policy_type_order: i64,
    reason: Option<String>,
    reason_code_display_name: Option<String>,
    reason_code_id: Option<String>,
    request_range_type: String,
    requested_by: String,
    requested_period: String,
    start_date: String,
    start_date_portion: String,
    states: Option<String>,
    status: String,
    unit: String,
}
