name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always


jobs:
  linux:
    name: Rust project - fmt, build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          # - beta
          # - nightly
    steps:
      - uses: actions/checkout@v3
      - name: Rustup update and set default toolchain
        run: |
          rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Cargo fmt
        run: cargo fmt --all
      - name: Cargo build
        run: cargo build --verbose
      - name: Cargo test
        run: make test
