name: Publish Artifacts

on:
  # the 1st condition
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

env:
  CARGO_TERM_COLOR: always


jobs:
  linux:
    name: Linux binary
    # the 2nd condition
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          # - beta
          # - nightly
    steps:
      - uses: actions/checkout@v3
      - name: Rustup update and set default toolchain
        run: |
          rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Cargo build release
        run: |
          cargo build --release --target=x86_64-unknown-linux-gnu
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bobinator_x86_64-unknown-linux-gnu
          path: target/x86_64-unknown-linux-gnu/release/bobinator

  windows:
    name: Windows binary
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        toolchain:
          - stable
          # - beta
          # - nightly
    steps:
      - uses: actions/checkout@v3
      - name: Rustup update and set default toolchain
        run: |
          rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Cargo build release
        run: |
          cargo build --release --target=x86_64-pc-windows-msvc
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bobinator_x86_64-pc-windows-msvc
          path: target/x86_64-pc-windows-msvc/release/bobinator.exe
